// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEJQ5nDrKIOTv6vT6qSbzL7WvqrmoCtKo',
    appId: '1:164718166744:web:4745ffcefbb930d5ffcdad',
    messagingSenderId: '164718166744',
    projectId: 'cards-8f99f',
    authDomain: 'cards-8f99f.firebaseapp.com',
    storageBucket: 'cards-8f99f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmzNlXRhDvyHjtV2BbDGaSB3c-73AUYc0',
    appId: '1:164718166744:android:812c7ec9bccbeda6ffcdad',
    messagingSenderId: '164718166744',
    projectId: 'cards-8f99f',
    storageBucket: 'cards-8f99f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFThk4XaYigtR3gMU6BBTC68cKlbfejfI',
    appId: '1:164718166744:ios:ea5b8af22f66a867ffcdad',
    messagingSenderId: '164718166744',
    projectId: 'cards-8f99f',
    storageBucket: 'cards-8f99f.appspot.com',
    iosBundleId: 'com.example.feedcards',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFThk4XaYigtR3gMU6BBTC68cKlbfejfI',
    appId: '1:164718166744:ios:ea5b8af22f66a867ffcdad',
    messagingSenderId: '164718166744',
    projectId: 'cards-8f99f',
    storageBucket: 'cards-8f99f.appspot.com',
    iosBundleId: 'com.example.feedcards',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEJQ5nDrKIOTv6vT6qSbzL7WvqrmoCtKo',
    appId: '1:164718166744:web:213660f7807a6ad6ffcdad',
    messagingSenderId: '164718166744',
    projectId: 'cards-8f99f',
    authDomain: 'cards-8f99f.firebaseapp.com',
    storageBucket: 'cards-8f99f.appspot.com',
  );

}